# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=800)),
                ('card_date', models.DateTimeField(verbose_name='review date')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('deck_date', models.DateTimeField(verbose_name='review date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udeck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flipcards.Deck'),
        ),
        migrations.AddField(
            model_name='cards',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucards', to=settings.AUTH_USER_MODEL),
        ),
    ]
