# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcards', '0002_auto_20170211_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Geography', 'Geography'), ('History', 'History'), ('Literature', 'Literature'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Fun', 'Fun'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
