# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0002_deck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
