# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0005_auto_20161128_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
