# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0006_auto_20161214_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_date',
            field=models.IntegerField(default=2000, verbose_name='year published'),
        ),
    ]
