# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0007_auto_20161214_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=800)),
                ('deck_date', models.IntegerField(default=2000, verbose_name='year published')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='fcga.Deck')),
            ],
        ),
    ]
