# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0008_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='deck_date',
            new_name='card_date',
        ),
    ]
