# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0009_auto_20161217_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='review date time'),
        ),
    ]
