# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcga', '0010_auto_20161217_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.IntegerField(default=2000, verbose_name='year published'),
        ),
    ]
